version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/packages/framework"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/persistence"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/cache-redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/bref-adapter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/query-builder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/auth-jwt"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/migrations"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/mcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/queue"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/queue-redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/queue-sql"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/storage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/revolt-http-client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/aws-sigv4"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/storage-s3"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/queue-sqs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/queue-rabbitmq"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/mailer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/search-opensearch"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/telemetry"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/session"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/pingpong"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/packages/skeleton"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
