<?php

declare(strict_types=1);

namespace Kinetis\Cache;

use Kinetis\Cache\Exception\CacheWriteException;
use Kinetis\Cache\Exception\UnexportableArtifactException;
use ParseError;
use Throwable;
use UnitEnum;

/**
 * Reads and publishes the one compiled artifact,
 * `.kinetis-cache/compiled.php` — every section a `Compiler::compile()`
 * run produces, in a single file a boot loads whole.
 *
 * The file is plain PHP returning a literal array, so `require` hands
 * back the data with no decoding step, and OPcache's shared opcode cache
 * — keyed by realpath, shared across every worker process on a host —
 * skips re-parsing it from the second request on.
 *
 * A publish never mutates the live file. {@see write()} renders the whole
 * artifact into a uniquely-named temporary file beside it, requires that
 * file back to confirm it returns the array it was rendered from, and
 * only then `rename()`s it onto the real path — atomic within
 * one directory on POSIX, a directory-entry swap rather than a data
 * copy. A reader therefore sees the complete previous artifact or the
 * complete new one, never a partial write, and a failed publish leaves
 * whatever was already there untouched.
 *
 * The rename is followed by `opcache_invalidate()` where OPcache is
 * loaded. That reaches the calling process's own OPcache and nothing
 * else. A boot that compiles in memory and publishes the result goes on
 * serving that in-memory bundle, so invalidation is not what makes the
 * fallback publish usable. What it covers is narrower: this process may
 * already have required a stale or rejected artifact from this path,
 * and clearing that entry makes a later include by this same process
 * eligible to see the replacement. It does not reach a separate serving
 * pool. A `bin/kinetis build` run from the CLI cannot
 * invalidate an FPM pool's or a FrankenPHP worker's shared opcodes for
 * the reused path, and under `opcache.validate_timestamps=0` those
 * processes keep serving the previous file until they restart. The
 * deployment shape that needs no invalidation at all is the normal one:
 * build `compiled.php` into the immutable artifact or image, then start
 * workers against it. Running `build` against a live shared deployment
 * requires restarting the serving pool or workers before the new
 * artifact is guaranteed active.
 *
 * Concurrent publishers are not serialized: workers cold-starting against
 * a missing artifact each compile once and each publish their own copy,
 * and whichever rename lands last is what later readers get. Every
 * racing compile discovers the same classes, so the cost is bounded,
 * one-time-per-process work rather than a difference in what is served.
 */
final class CacheStore
{
    public const string ARTIFACT_FILENAME = 'compiled.php';

    public function __construct(
        private readonly string $directory,
    ) {}

    /**
     * The published artifact, reconstructed into the section objects a
     * boot uses, or null when there is nothing usable to read: no file,
     * a file whose PHP is malformed (a truncated write, disk corruption,
     * tampering), a value that is not an array, or one carrying a
     * `formatVersion` this build does not speak.
     *
     * A section's own `fromArray()` refusal propagates as a
     * {@see \Kinetis\Cache\Exception\CacheArtifactExceptionInterface};
     * {@see BootSequence} classifies that alongside the reconstructions
     * it performs itself, so both reach the same recompile.
     *
     * @throws \Kinetis\Cache\Exception\CacheArtifactExceptionInterface
     */
    public function load(): ?CompiledCache
    {
        $path = $this->path();

        if (!is_file($path)) {
            return null;
        }

        try {
            /** @var mixed $data */
            $data = require $path;
        } catch (ParseError) {
            // Caught by type, and only this one: a persisted artifact's
            // intrinsic failure mode is that its PHP is malformed, which
            // is exactly as unusable as a missing file. Nothing else a
            // file's top-level code might raise is classified this way —
            // every artifact is generated by var_export(), never
            // hand-authored.
            return null;
        }

        if (!is_array($data) || ($data['formatVersion'] ?? null) !== CacheFormat::VERSION) {
            return null;
        }

        /** @var array<array-key, mixed> $data */
        return CompiledCache::fromArray($data);
    }

    /**
     * Publishes $cache as the whole artifact, replacing whatever is
     * there.
     *
     * A value with no `var_export()` representation is refused before
     * anything is written, as an {@see UnexportableArtifactException}:
     * that is a defect in what was compiled, not a failure to persist
     * it, and the two are separated here because the runtime's
     * compile-in-memory fallback continues past the second and never
     * past the first.
     *
     * @throws UnexportableArtifactException
     * @throws CacheWriteException
     */
    public function write(CompiledCache $cache): void
    {
        $data = $cache->toArray();
        self::assertExportable($data);

        // The @ is deliberate, not a suppressed real error: two
        // publishers can both observe the directory missing and race to
        // create it, and mkdir() failing for whichever loses that race is
        // expected. The is_dir() recheck is what distinguishes it from a
        // genuine failure to create the directory.
        if (!is_dir($this->directory) && !@mkdir($this->directory, 0775, true) && !is_dir($this->directory)) {
            throw CacheWriteException::couldNotCreateDirectory($this->directory);
        }

        $path = $this->path();
        $temporaryPath = $path . '.' . bin2hex(random_bytes(8)) . '.tmp';

        try {
            self::writeFile($temporaryPath, "<?php\n\nreturn " . var_export($data, true) . ";\n");
            self::assertReconstructs($temporaryPath, $data);
        } catch (Throwable $failure) {
            @unlink($temporaryPath);

            throw $failure;
        }

        // The @ matches mkdir()'s above: couldNotPublish() names the
        // exact path, so a second raw PHP warning for the same failure
        // adds nothing.
        if (!@rename($temporaryPath, $path)) {
            @unlink($temporaryPath);

            throw CacheWriteException::couldNotPublish($path);
        }

        // This process's own OPcache only — see the class docblock for
        // what that does and does not cover.
        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }
    }

    public function path(): string
    {
        return $this->directory . '/' . self::ARTIFACT_FILENAME;
    }

    /**
     * Every byte, or an error. `file_put_contents()` reports a short
     * write as a smaller count rather than a failure, and an artifact
     * missing its tail is a `ParseError` on the next boot instead of the
     * publish failure it actually is.
     */
    private static function writeFile(string $path, string $contents): void
    {
        $written = @file_put_contents($path, $contents);

        if ($written !== strlen($contents)) {
            throw CacheWriteException::couldNotWriteTemporaryFile($path);
        }
    }

    /**
     * Requires the staged file back and checks it returns the array it
     * was rendered from, before that file becomes the one every boot
     * reads. This is the only point at which "what was written" and
     * "what a reader will get" can be compared at all — afterwards a
     * reader's disagreement with the writer is a failed boot.
     *
     * @param array<array-key, mixed> $expected
     */
    private static function assertReconstructs(string $path, array $expected): void
    {
        try {
            // require, not require_once: the comparison below needs the
            // array the artifact returns, and a repeated include of the
            // same path yields true instead.
            /** @var mixed $reread */
            $reread = require $path; // NOSONAR
        } catch (ParseError) {
            throw CacheWriteException::couldNotVerify($path);
        }

        if ($reread !== $expected) {
            throw CacheWriteException::couldNotVerify($path);
        }
    }

    /**
     * `var_export()` renders an object as a `\SomeClass::__set_state(...)`
     * call most classes cannot replay, so an object anywhere in the
     * artifact produces a file that cannot be required back. Refused
     * here, naming where the object sits, rather than discovered on the
     * first boot that reads it.
     *
     * An enum case is the exception, and the only one: `var_export()`
     * writes it as `\Status::Active`, which a reload evaluates back to
     * the very same case — enum cases are process-wide singletons, so
     * the reconstructed artifact is identical to the one written, and
     * `assertReconstructs()` below compares it as such.
     *
     * A parameter default that constructs an object never reaches this
     * check: {@see \Kinetis\Reflection\ParameterDefault} refuses it
     * while the plan is derived, so a live worker and a build fail on
     * the same declaration. What reaches here is the rest of the
     * artifact — a discovery section carrying a value it has not reduced
     * to plain data.
     *
     * @param array<array-key, mixed> $data
     */
    private static function assertExportable(array $data, string $keyPath = ''): void
    {
        foreach ($data as $key => $value) {
            $valuePath = $keyPath === '' ? (string) $key : "{$keyPath}.{$key}";

            if (is_object($value) && !$value instanceof UnitEnum) {
                throw UnexportableArtifactException::object($valuePath, $value::class);
            }

            if (is_array($value)) {
                self::assertExportable($value, $valuePath);
            }
        }
    }
}
